#!/bin/sh

oldswaybg="$(pid of swaybg)"
swaymsg "output * bg /home/baleksa/Pictures/green_village.jpg fill"
kill "$oldswaybg"

makoctl set-mode light

notify-send --app-name="darkman" --urgency=low -i /usr/share/icons/gnome/32x32/status/weather-clear.png "Switching to light mode"
