#!/bin/sh

oldswaybg="$(pidof swaybg)"
(swaybg -i ~/Pictures/green_village.jpg -o \* -m fill &)
kill "$oldswaybg"

makoctl set-mode light

notify-send --app-name="darkman" --urgency=low -i /usr/share/icons/gnome/32x32/status/weather-clear.png "Switching to light mode"
