#!/bin/sh

. ./utils.sh
. ./base.sh
. ./extra.sh

do_job "Adding script which sets XDG_RUNTIME_DIR for all users on boot:" \
	setup_xdg_runtime_dir

do_job "Init xbps and install helper packages" init_xbps

message "INSTALLING ZSH AND SETTING IT AS DEFAULT SHELL"
xi -y zsh
chsh -s /bin/zsh

message "INSTALLING MESA DRIVERS CPU FIRMWARE"
xi -y mesa-dri mesa-vaapi mesa-vdpau
xi -y intel-ucode mesa-vulkan-intel linux-firmware-intel intel-video-accel
xi -y linux-firmware-amd vulkan-loader
xi -y nvidia

message "MAKE POWER GROUP AND ENABLE IT'S MEMBERS TO RUN POWER COMMANDS"
groupadd power
mkdir -p '/etc/sudoers.d'
[ -d '/etc/sudoers.d' ] &&
	sudo tee '/etc/sudoers.d/power' <<-'script'
		## Admin user group is allowed to execute halt and reboot
		%power ALL=NOPASSWD: /usr/bin/halt, /usr/bin/reboot, /usr/bin/poweroff, /usr/bin/zzz, /usr/bin/ZZZ
	script
chmod 0440 '/etc/sudoers.d/power'

message "DBUS"
xi -y dbus && add_service dbus

message "LOGGING"
xi -y socklog-void &&
	add_service socklog_unix &&
	add_service nanoklogd
usermod -a -G socklog "$USER"

message "MAKE LINUX USE LOCALTIME FOR TIME TO BE ACCURATE IF DUALBOOTING AND SET CHRONY"
echo 'export HARDWARECLOCK=localtime' | sudo tee -a /etc/rc.conf
xi -y chrony && add_service chronyd

message "Install cronie and set up its service"
xi -y cronie
ln -s /etc/sv/cronie /var/service

message "TLP FOR POWER MANAGEMENT"
xi -y tlp && add_service tlp

message "SEATD"
xi -y seatd && add_service seatd && sudo usermod -a -G _seatd "$USER"

message "SWAY"
xi -y sway swayidle swaylock
xi -y qt5-wayland qt6-wayland
xi -y kwayland

message "IWD"
xi -y iwd && add_service iwd && printf '[General]\nUseDefaultInterface=true' | sudo tee -a /etc/iwd/main.conf

message "ZSH"
xi -y zsh-autosuggestions zsh-completions zsh-syntax-highlighting zsh-history-substring-search

message "PIPEWIRE, ALSA AND BLUETOOTH"
xi -y pipewire libspa-bluetooth alsa-pipewire wireplumber
mkdir -p /etc/pipewire
sed '/path.*=.*pipewire-media-session/s/{/#{/' \
	/usr/share/pipewire/pipewire.conf >/etc/pipewire/pipewire.conf
sudo mkdir -p /etc/alsa/conf.d
sudo ln -s /usr/share/alsa/alsa.conf.d/50-pipewire.conf /etc/alsa/conf.d
sudo ln -s /usr/share/alsa/alsa.conf.d/99-pipewire-default.conf /etc/alsa/conf.d
xi -y bluez && add_service bluetoothd && sudo usermod -a -G bluetooth "$USER"

message "STOW DOTFILES"
xi -y stow
stow ./*/

message "FLATPAK AND FLATPAK APPS (zoom)"
xi -y flatpak
sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak --user install flathub us.zoom.Zoom

message "Install terminals: wezterm and foot"
xi -y wezterm wezterm-terminfo
xi -y foot foot-terminfo

message "Install packages for development"
xi -y python3 python3-devel lua lua-devel

message "MANPAGES"
xi -Su -y xi man-pages-devel man-pages-posix
makewhatis

message "Set udkiskie polkit rules to enable (un)mounting drives for regular users"
polkit_rules_d="/etc/pokit-1/rules.d"
sudo mkdir -p "$polkit_rules_d"
[ -d "$polkit_rules_d" ] &&
	sudo tee "$polkit_rules_d/50-udiskie.rules" <<'script'
polkit.addRule(function(action, subject) {
  var YES = polkit.Result.YES;
  var permission = {
    // required for udisks1:
    "org.freedesktop.udisks.filesystem-mount": YES,
    "org.freedesktop.udisks.luks-unlock": YES,
    "org.freedesktop.udisks.drive-eject": YES,
    "org.freedesktop.udisks.drive-detach": YES,
    // required for udisks2:
    "org.freedesktop.udisks2.filesystem-mount": YES,
    "org.freedesktop.udisks2.encrypted-unlock": YES,
    "org.freedesktop.udisks2.eject-media": YES,
    "org.freedesktop.udisks2.power-off-drive": YES,
    // required for udisks2 if using udiskie from another seat (e.g. systemd):
    "org.freedesktop.udisks2.filesystem-mount-other-seat": YES,
    "org.freedesktop.udisks2.filesystem-unmount-others": YES,
    "org.freedesktop.udisks2.encrypted-unlock-other-seat": YES,
    "org.freedesktop.udisks2.eject-media-other-seat": YES,
    "org.freedesktop.udisks2.power-off-drive-other-seat": YES
  };
  if (subject.isInGroup("storage")) {
    return permission[action.id];
  }
});
script
sudo chmod 644 "$polkit_rules_d/50-udiskie.rules"

message "INSTALL OTHER PACKAGES"
xi -Su -y
xi -y "$(cat ./void_packages.txt)"

message "Set default applications for various mime types"
xdg-mime default org.pwmt.zathura.desktop application/pdf
xdg-mime default org.pwmt.zathura.desktop application/epub+zip
xdg-mime default nvim.desktop text/english text/plain text/x-makefile text/x-c++hdr text/x-c++src text/x-chdr text/x-csrc text/x-java text/x-moc text/x-pascal text/x-tcl text/x-tex application/x-shellscript text/x-c text/x-c++
xdg-mime default lf.desktop inode/directory

message "REBOOTING NOW"
reboot now
