#!/bin/sh

add_service() {
	[ ! -d /var/service/"$1" ] && sudo ln -s /etc/sv/"$1" /var/service
}

message() {
	echo "$1:"
	echo "=================="
}

message "Make XDG_RUNTIME_DIR and set its owner for each user"
sudo tee -a /etc/rc.local <<'script'
for uid in $(awk -F ':' '$3>=1000 {print ""$3":"$1}' /etc/passwd); do
    dirname=$(echo "$uid" | cut -d: -f1)
    usernm=$(echo "$uid" | cut -d: -f2)
    mkdir /run/user/"$dirname"
    chmod 700 /run/user/"$dirname"
    chown "$usernm" /run/user/"$dirname"
done
script

message "Make a script that sets XDG_RUNTIME_DIR for every user on boot"
sudo tee -a /etc/profile.d/set_xdg_runtime_dir.sh <<'script'
#!/bin/sh
if (( "$(id -u)" >= 1000 )); then
	export XDG_RUNTIME_DIR=/run/user/$(id -u)
fi
script

message "INSTALLING XTOOLS AND ENABLING NONFREE REPO"
sudo xbps-install -Su -y xtools void-repo-nonfree

message "INSTALLING ZSH AND SETTING IT AS DEFAULT SHELL"
xi -y zsh
chsh -s /bin/zsh

message "INSTALLING MESA DRIVERS CPU FIRMWARE"
xi -y mesa-dri mesa-vaapi mesa-vdpau
xi -y intel-ucode mesa-vulkan-intel linux-firmware-intel intel-video-accel
xi -y linux-firmware-amd vulkan-loader
xi -y nvidia

message "DBUS"
xi -y dbus && add_service dbus

message "LOGGING"
xi -y socklog-void &&
	add_service socklog_unix &&
	add_service nanoklogd
usermod -a -G socklog "$USER"

message "MAKE LINUX USE LOCALTIME FOR TIME TO BE ACCURATE IF DUALBOOTING AND SET CHRONY"
echo 'HARDWARECLOCK=localtime' | sudo tee -a /etc/rc.conf
xi -y chrony && add_service chronyd

message "TLP FOR POWER MANAGEMENT"
xi -y tlp && add_service tlp

message "SEATD"
xi -y seatd && add_service seatd && sudo usermod -a -G _seatd "$USER"

message "SWAY"
xi -y sway swayidle swaylock
# xi -y qt5-wayland qt6-wayland
# xi -y kwayland

message "IWD"
xi -y iwd && add_service iwd && printf '[General]\nUseDefaultInterface=true' | sudo tee -a /etc/iwd/main.conf

message "ZSH"
xi -y zsh-autosuggestions zsh-completions zsh-syntax-highlighting zsh-history-substring-search

message "PIPEWIRE, ALSA AND BLUETOOTH"
xi -y pipewire libspa-bluetooth alsa-pipewire wireplumber
mkdir -p /etc/pipewire
sed '/path.*=.*pipewire-media-session/s/{/#{/' \
	/usr/share/pipewire/pipewire.conf >/etc/pipewire/pipewire.conf
sudo mkdir -p /etc/alsa/conf.d
sudo ln -s /usr/share/alsa/alsa.conf.d/50-pipewire.conf /etc/alsa/conf.d
sudo ln -s /usr/share/alsa/alsa.conf.d/99-pipewire-default.conf /etc/alsa/conf.d
xi -y bluez && add_service bluetoothd && sudo usermod -a -G bluetooth "$USER"

message "STOW DOTFILES"
xi -y stow
stow ./*/

message "FLATPAK AND FLATPAK APPS (zoom)"
xi -y flatpak
sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak --user install flathub us.zoom.Zoom

message "INSTALL OTHER PACKAGES"
xi -Su -y
xi -y "$(cat ./void_packages.txt)"

message "MANPAGES"
xi -Su -y xi man-pages-devel man-pages-posix
makewhatis

message "REBOOTING NOW"
sudo reboot now
