theme = "everforest_light_hard_mod"
[editor]
line-number = "relative"
scroll-lines = 1
cursorline = true
auto-save = false
completion-trigger-len = 1
true-color = true
color-modes = true
auto-pairs = true
rulers = [120]
idle-timeout = 50

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "┆"
# character = "▏"

[editor.lsp]
display-messages = true
display-inlay-hints = false

[editor.statusline]
left = [
	"mode",
	"spinner",
	"file-name",
	"file-type",
	"total-line-numbers",
	"file-encoding",
]
center = []
right = [
	"selections",
	"primary-selection-length",
	"position",
	"position-percentage",
	"spacer",
	"diagnostics",
	"workspace-diagnostics",
	"version-control",
]

[editor.gutters]
layout = ["line-numbers", "spacer", "diff"]
