#!/bin/sh

while true; do
	perc="$(cat /sys/class/power_supply/BAT0/capacity)"
	status="$(cat /sys/class/power_supply/BAT0/status)"

	if [ "$status" = "Charging" ] && [ "$perc" -gt 80 ]; then
		swaynag -t warning -m "Disconnect charger please!"
	elif [ "$status" = "Discharging" ] && [ "$perc" -lt 50 ]; then
		swaynag -t warning -m "Connect charger please!"
	fi

	sleep 5m
done
