#!/bin/sh

# Edit an old or make a new script

if [ "$#" = "0" ]; then
	cd "$MYSCRIPTS_DIR" || exit
	script="$(fd -t file . | fzf)"
	[ "$script" = "" ] && exit
else
	script="$MYSCRIPTS_DIR/$1"
	if [ ! -f "$script" ]; then
		touch "$script"
		chmod +x "$script"
	fi
fi
"$EDITOR" "$script"
[ -f "$script" ] && [ ! -s "$script" ] && rm "$script"
