#!/bin/sh

# Edit an old or make a new script

if [ "$#" = "0" ]; then
	script="$(find -H "$MYSCRIPTS_DIR" -type f | fzf)"
	script=${script:=$MYSCRIPTS_DIR}
else
	script="$MYSCRIPTS_DIR/$1"
	if [ ! -f "$script" ]; then
		touch "$script"
		chmod +x "$script"
	fi
fi
"$EDITOR" "$script"
[ -e "$script" ] && [ ! -s "$script" ] && rm "$script"
