#!/bin/sh

# Edit an old or make a new note

if [ "$#" = "0" ]; then
	note="$(find -H "$MYNOTES_DIR" -type d,f | fzf)"
	if [ "$note" = "" ]; then
		"$EDITOR" "$MYNOTES_DIR"
		exit
	fi
else
	note="$MYNOTES_DIR/$1"
fi
echo "Picked: $note"

if [ -d "$note" ]; then
	echo "Enter filename for the note:"
	read -r fname
	note="$note/$fname"
fi

if [ ! -f "$note" ]; then
	# touch "$note"
	echo "Enter a title for the note:"
	read -r title
	printf "%s\ntitle: \"%s\"\ncreated: \"%s\"\n%s\n" '---' "$title" "$(date -u -Is)" '---' >>"$note"
fi

"$EDITOR" "$note"
[ -e "$note" ] && [ ! -s "$note" ] && rm "$note"
