#!/bin/sh

set -o errexit

if ! rbw unlocked >/dev/null; then
	rbw unlock >/dev/null
fi
rbw get "$(rbw list --fields name,user,id | fzf | cut -f3)" | wl-copy --paste-once
sleep 5m && rbw lock >/dev/null &
# There is a bug where pinentry process stays open and eats cpu
pkill pinentry
