#!/bin/sh
curr_time_h="$(date +%H)"
day_h="${DAY_H:-06}"
night_h="${NIGHT_H:-20}"
if [ "$curr_time_h" -ge "$night_h" ]; then
	darkman set dark
elif [ "$curr_time_h" -lt "$day_h" ]; then
	darkman set dark
else
	darkman set light
fi
