#!/bin/sh

# Script that sets my three monitor setup, opens apps and places them as I desire.

# Using pgrep is not as portable as ps cax | grep command but it's much cleaner.
if ! pgrep firefox 2>/dev/null; then
	swaymsg workspace 1
	"$BROWSER" &
	sleep 2s
fi

swaymsg workspace portrait output DP-2, workspace portrait
swaymsg workspace extra output DP-2, workspace extra, layout tabbed

# swaymsg exec "$BROWSER --new-instance -P extra --name 'Firefox-extra'"

# zathura ~/notes/TODO.pdf &
# pid=$!
# (
# while ! swaymsg "[pid=${pid}] move workspace extra" >/dev/null 2>&1; do true; done
# ) &

swaymsg workspace portrait
swaymsg workspace 2
