#!/bin/sh

# Script that sets my three monitor setup, opens apps and places them as I desire.

# Using pgrep is not as portable as using ps cax | grep command but it's much cleaner.
# if ! pgrep firefox 2>/dev/null; then
# 	swaymsg "workspace 1, exec \$BROWSER, workspace 2"
# fi

swaymsg workspace extra, layout tabbed

swaymsg workspace portrait
swaymsg workspace 2
