#!/bin/sh

set -o errexit

analog_name='alsa_output.pci-0000_00_1f.3.analog-stereo'
hdmi_name='alsa_output.pci-0000_00_1f.3.hdmi-stereo' 
wpinfo="$(wpctl status -n)"

analog_id="$(printf '%s' "$wpinfo" | grep "$analog_name" | head -1 | tr -d '[:blank:]*│' | cut -d'.' -f1)"
hdmi_id="$(printf '%s' "$wpinfo" | grep "$hdmi_name" | head -1 | tr -d '[:blank:]*│' | cut -d'.' -f1)"

default_audio_sink="$(wpctl status | grep Audio/Sink)"

case "$default_audio_sink" in
*analog*)
	wpctl set-default "$hdmi_id"
	;;
*hdmi*)
	wpctl set-default "$analog_id"
	;;
esac
