#!/bin/sh

window_title="termlauncher"

case "$TERM" in
wezterm)
	wezterm --config 'window_close_confirmation="NeverPrompt"' \
		start --class="$window_title" -- "$1"
	;;
*foot*)
	start_foot -T"$window_title" "$1"
	;;
esac
