#!/bin/sh

# Same as termlauncher but makes window transparent.

window_title="termlauncher"

case "$TERM" in
wezterm)
	wezterm --config 'window_close_confirmation="NeverPrompt"' \
		--config 'window_background_opacity=0.5' \
		--config 'text_background_opacity=0.7' \
		start --class="$window_title" -- "$@"
	;;
*foot*)
	foot -T"$window_title" -o "colors.alpha=0.1" "$@"
	;;
esac
