#!/bin/env python3

import subprocess
import sys
import time

if len(sys.argv) - 1 > 0:
    wifi_networks = sys.argv[1:]
else:
    print("Usage: test_wifi [SSID ...]")
    exit(1)

connect_command = ["iwctl", "station", "wlo1", "connect"]
scan_command = ["iwctl", "station", "wlo1", "scan"]
get_networks_command = ["iwctl", "station", "wlo1", "get-networks"]
speedtest_command = ["speedtest-cli", "--csv"]
DOWNLOAD_INDEX = 6
n_cycles = 1
wait_for_connection_sec = 5
test_results = {}

print(f"Testing wifi speeds for networks: {wifi_networks}")

subprocess.run(scan_command, stdout=subprocess.DEVNULL)
subprocess.run(get_networks_command, stdout=subprocess.DEVNULL)

for network in wifi_networks:
    subprocess.run(
        connect_command + [network],
    )
    time.sleep(wait_for_connection_sec)
    speed_bit_s = float(
        subprocess.run(speedtest_command, stdout=subprocess.PIPE).stdout.split(b",")[
            DOWNLOAD_INDEX
        ]
    )
    bits_in_mbyte = 8 * 1024 * 1024
    speed_MB_s = speed_bit_s / bits_in_mbyte
    test_results[network] = speed_MB_s

print("{:12}|{:>12}".format("SSID", "Speed"))
print("{:12} {:>12}".format("____", "_____"))
for ssid in wifi_networks:
    wifi_speed = test_results[ssid]
    print(f"{ssid:12}:{wifi_speed:10.2f}MB")
