#!/bin/sh

RED='\033[31m'
PURPLE='\033[35m'
GREEN='\033[32m'
NC='\033[0m' # No Color

do_job() {
    hello_msg="$1"
    shift
    bye_msg="$1"
    shift
    failed_msg="$1"
    shift
    colored_echo "$hello_msg" "$PURPLE"
    if "$@"; then
        colored_echo "$bye_msg" "$GREEN"
    else
        colored_echo "$failed_msg" "$RED"
    fi
}

colored_echo() {
	msg="$1"
	color="$2"
	echo "${color}${msg}${NC}"
}

do_job "Updating xbps packages:" "Done!" "Failed!" xi -Su

do_job "Updating sumneko lua language server:" "Done!" "Failed!" update_sumneko_lua_server

do_job "Updating neovim to the HEAD github branch." "Done!" "Failed!" update_neovim

do_job "Updating neovim packages with packer.nvim:" "\nDone!" "\nFailed!" nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'

do_job "Update all nvim-treesitter installed parsers:" "\nDone!" "\nFailed!" nvim --headless -c 'TSUpdate' -c "quitall"



