#!/bin/sh

# Update neovim to the HEAD github branch

while true; do
	printf "Do you wish to update neovim? [y/N]: "
	read -r yn
	case $yn in
	[Yy]*) break ;;
	*) exit ;;
	esac
done

cd "$GIT_REPOS_DIR/neovim" || exit

if [ "$1" != "--force" ] && [ "$(git pull)" = "Already up to date." ]; then
	echo "Neovim is up-to-date."
	exit 0
fi

make distclean && echo "Cleaned build dirs."
make CMAKE_BUILD_TYPE=RelWithDebInfo CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX=$HOME/.local"
build_status=$?
if [ "$build_status" = "0" ]; then
	echo "Built nvim. Now installing."
	rm -rf /home/baleksa/.local/share/nvim/runtime && echo "Removed old VIMRUNTIME"
	make CMAKE_INSTALL_PREFIX="$HOME/.local" install && echo "Installed nvim."
else
	echo "Building nvim failed with exit code $build_status!"
	exit $build_status
fi
