#!/bin/sh

# Update neovim to the HEAD github branch

while true; do
	printf "Do you wish to update neovim? [y/N]: "
	read -r yn
	case $yn in
	[Yy]*) break ;;
	*) exit ;;
	esac
done

cd "$GIT_REPOS_DIR/neovim" || exit
if [ "$(git pull)" = "Already up to date." ]; then
	echo "Repository is already up to date."
	exit 0
fi

make CMAKE_BUILD_TYPE=Release CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX=$HOME/.local"

make install

