#!/bin/sh

update_mason_packages() {
	nvim --headless \
		-c 'autocmd User MasonUpdateAllComplete quitall' \
		-c 'MasonUpdateAll'

}

update_python_lsp_extensions() {
	pylsp_path="$HOME/.local/share/nvim/mason/packages/python-lsp-server"
	cd "$pylsp_path" || {
		echo "Failed to cd to $pylsp_path"
		return 1
	}

	# shellcheck disable=1091
	. "$pylsp_path/venv/bin/activate" || {
		echo "Failed to activate python venv."
		return 1
	}

	pip uninstall -y pyls-isort isort \
		pylint flake8 pycodestyle \
		autopep8 yapf pyflakes pydocstyle
	status="$?"
	if [ "$status" -ne 0 ]; then
		echo "Removing useless pip packages failed."
		return "$status"
	fi
	pip install --no-input python-lsp-black pylsp-rope \
		python-lsp-ruff ruff black rope
	status="$?"
	if [ "$status" -ne 0 ]; then
		echo "Updating used pip packages failed."
		return "$status"
	fi

	deactivate || {
		echo "Failed to deactivate python venv."
		return 1
	}
}

update_mason_packages
status="$?"
if [ "$status" -ne 0 ]; then
	echo "Updating mason packages failed with error $status"
	exit "$status"
fi
update_python_lsp_extensions
status="$?"
if [ "$status" -ne 0 ]; then
	echo "Updating pylsp extension failed with error $status"
	exit "$status"
fi
 
exit 0
