#!/bin/sh

mason_packages_path="$HOME/.local/share/nvim/mason/packages"

update_mason_packages() {
	nvim --headless \
		-c 'autocmd User MasonUpdateAllComplete quitall' \
		-c 'MasonUpdateAll'

}

# update_solargraph_rails() {
# 	solargraph_path="$mason_packages_path/solargraph"
# 	cd "$solargraph_path" || {
# 		echo "Failed to cd to $solargraph_path"
# 		return 1
# 	}
#
# 	gem i --install-dir "$solargraph_path" \
# 		solargraph-rails
# }

update_python_lsp_extensions() {
	pylsp_path="$mason_packages_path/python-lsp-server"
	cd "$pylsp_path" || {
		echo "Failed to cd to $pylsp_path"
		return 1
	}

	# shellcheck disable=1091
	. "$pylsp_path/venv/bin/activate" || {
		echo "Failed to activate python venv."
		return 1
	}

	# pip uninstall -y pyls-isort isort \
	# 	pylint flake8 pycodestyle \
	# 	autopep8 yapf pyflakes pydocstyle
	# status="$?"
	# if [ "$status" -ne 0 ]; then
	# 	echo "Removing useless pip packages failed."
	# 	return "$status"
	# fi
	pip install --no-input pylsp-rope \
		python-lsp-ruff ruff rope
	status="$?"
	if [ "$status" -ne 0 ]; then
		echo "Updating used pip packages failed."
		return "$status"
	fi

	deactivate || {
		echo "Failed to deactivate python venv."
		exit 1
	}
}

# update_mason_packages
# status="$?"
# if [ "$status" -ne 0 ]; then
# 	echo "Updating mason packages failed with error $status"
# 	exit "$status"
# fi
update_python_lsp_extensions
status="$?"
if [ "$status" -ne 0 ]; then
	echo "Updating pylsp extension failed with error $status"
	exit "$status"
fi

# update_solargraph_rails
# status="$?"
# if [ "$status" -ne 0 ]; then
# 	echo "Adding solargraph-rails to solargraph failed with error $status"
# 	exit "$status"
# fi

exit 0
