#!/bin/sh

update_mason_packages() {
	nvim --headless \
		-c 'autocmd User MasonUpdateAllComplete quitall' \
		-c 'MasonUpdateAll'

}

update_python_lsp_extensions() {
	pylsp_path="$HOME/.local/share/nvim/mason/packages/python-lsp-server"
	[ -d "$pylsp_path" ] || exit 1
	cd "$pylsp_path" || {
		echo "Failed to cd to $HOME/.local/share/nvim/mason/packages/python-lsp-server"
		return 1
	}

	. "$pylsp_path/venv/bin/activate" || {
		echo "Failed to activate python venv."
		return 1
	}

	pip uninstall pyls-isort isort \
		pylint flake8 pycodestyle \
		autopep8 yapf pyflakes pydocstyle
	status="$?"
	if [ "$status" -ne 0 ]; then
		echo "Removing useless pip packages failed."
		return "$status"
	fi
	pip install python-lsp-black pylsp-rope \
		python-lsp-ruff ruff black rope
	status="$?"
	if [ "$status" -ne 0 ]; then
		echo "Updating used pip packages failed."
		return "$status"
	fi

	deactivate || {
		echo "Failed to deactivate python venv."
		return 1
	}
}

cwd="$PWD"
update_mason_packages
status="$?"
if [ "$status" -ne 0 ]; then
	echo "Updating mason packages failed with error $status"
	exit "$status"
fi
update_python_lsp_extensions
status="$?"
if [ "$status" -ne 0 ]; then
	echo "Updating pylsp extension failed with error $status"
	exit "$status"
fi
cd "$cwd" || {
	echo "Failed to return to $cwd".
	exit 1
}
exit 0
