#!/bin/sh

RED='\033[31m'
PURPLE='\033[35m'
GREEN='\033[32m'
NC='\033[0m' # No Color

do_job() {
	hello_msg="$1"
	shift
	bye_msg="$1"
	shift
	failed_msg="$1"
	shift
	colored_echo "$hello_msg" "$PURPLE"
	if "$@"; then
		colored_echo "$bye_msg" "$GREEN"
	else
		colored_echo "$failed_msg" "$RED"
	fi
}

colored_echo() {
	msg="$1"
	color="$2"
	echo "${color}${msg}${NC}"
}

do_job "Updating xbps packages." "Done!" "Failed!" xi -Syu

do_job "Updating neovim to the HEAD github branch." "Done!" "Failed!" update_neovim

do_job "Updating neovim packages via lazy.nvim." "\nDone!" "\nFailed!" \
	nvim --headless "+Lazy! sync" +qa

# You need to call TSUpdateSync to update syncroniously because async command doesn't work in scripts. I guess main process quits and take other threads and forks with it.
do_job "Updating all installed nvim-treesitter parsers." "\nDone!" "\nFailed!" \
	nvim --headless -c 'TSUpdateSync all' -c "quitall"

do_job "Updating Mason nvim packages:" "\nDone!" "\nFailed!" update_mason_nvim

do_job "Updating rust toolchain:" "\nDone!" "\nFailed!" rustup update
