#!/bin/sh

focused_monitor="$(swaymsg -t get_outputs | jq '.[] | select(.focused == true) | .name')"

if [ "$focused_monitor" = '"eDP-1"' ]; then
	exec wezterm --config "font_size=15" "$@"
else
	exec wezterm "$@"
fi
