#!/bin/sh

# shellcheck disable=2154
alias ec='pick_and_nvim "$HOME"/.config'
alias ep='edit_project'

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'
# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'
alias p='ps aux | grep '

alias luamake=/home/baleksa/repositories/lua-language-server/3rd/luamake/luamake

alias g='lazygit'
alias m="git checkout main"
alias s="git checkout stable"
alias gc="git commit"
alias ga="git add"
alias gs="git status"
alias gp="git push"
alias gd="git diff"

alias f='zi'

alias ls='ls --color=auto'
alias la='ls -a'
alias ll='ls -la'

alias pip='pip3'

alias xqr='xbps-query -Rs'
alias xr='sudo xbps-remove'

alias luamake='/home/baleksa/Repositories/lua-language-server/3rd/luamake/luamake'

alias clangse='clang -Wall -g3 -Werror -pedantic -std=c11'
alias c='clang -Wall -g3 -Werror -pedantic -std=c11'
alias c++='clang++ -Wall -g3 -Werror -pedantic -std=c++11'

alias t='todo.sh -d ~/.config/todo/todo.conf'

alias es='edit_script'
alias en='edit_note'

alias u='update_all'

alias d='sdcv --color'

alias st='sync_todo'
alias stc='rclone bisync gdrive_void_hpi5:todo /home/baleksa/Documents/todo --exclude "todo.txt.bak" --exclude "report.txt"'

alias reboot='sudo reboot'
alias poweroff='sudo poweroff'
alias halt='sudo halt'
alias halt='sudo halt'
alias zzz='sudo zzz'
alias ZZZ='sudo ZZZ'
alias shutdown='sudo shutdown'
