#!/bin/sh

# Session
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=sway
export XDG_CURRENT_DESKTOP=sway

# Wayland stuff
export MOZ_ENABLE_WAYLAND=1
export QT_QPA_PLATFORM=wayland
export SDL_VIDEODRIVER=wayland
export _JAVA_AWT_WM_NONREPARENTING=1
export GTK_BACKEND=wayland
# export WAYLAND_DEBUG=1 # Uncomment this line to enable more verbose logging

# D-Bus
# If the session bus is not available it is spawned and wrapper round our program
# Otherwise we spawn our program directly
# if [ -z "${DBUS_SESSION_BUS_ADDRESS}" ]; then
#     drs=dbus-run-session
# fi
if [ -z "$DISPLAY" ] && [ "$(tty)" = "/dev/tty1" ]; then
	# exec ${drs} sway
	exec dbus-run-session sway
fi
