#!/bin/sh

# Session
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=sway
export XDG_CURRENT_DESKTOP=sway

# Wayland stuff
export MOZ_ENABLE_WAYLAND=1
export QT_QPA_PLATFORM=wayland-egl
export SDL_VIDEODRIVER=wayland
export _JAVA_AWT_WM_NONREPARENTING=1
export GTK_BACKEND=wayland
export ELM_DISPLAY=wl
# export WAYLAND_DEBUG=1 # Uncomment this line to enable more verbose logging

if [ "$DISPLAY" = "" ] && [ "$(tty)" = "/dev/tty1" ]; then
	exec dbus-run-session sway
fi
