#!/bin/zsh


HISTSIZE=1000000
SAVEHIST=1000000

export GIT_REPOS_DIR=~/repositories

export FZF_DEFAULT_COMMAND='fd -H .'
export FZF_CTRL_R_OPTS='--layout=reverse'

export MANPAGER='nvim +Man!'
export MANWIDTH=999

export VOIDNSRUN_DIR=/glibc
export VOIDNSUNDO_BIN=/usr/local/bin/voidnsundo

export STARDICT_DATA_DIR=~/.config/stardict
export SDCV_PAGER="nvim +Man!"

#export GTK_BACKED=wayland

eval "$(zoxide init zsh)"

# eval "`pip completion --zsh`"
