#!/bin/zsh


alias j='z'
alias f='zi'
alias g='lazygit'

alias ec='nvim "$(fd -LH . /home/baleksa/.config | fzf || .)"'
alias nvimrc='nvim ~/.config/nvim/'
alias zshrc='nvim ~/.config/zsh/'

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

# gpg encryption
# verify signature for isos
alias gpg-check="gpg2 --keyserver-options auto-key-retrieve --verify"
# receive the key of a developer
alias gpg-retrieve="gpg2 --keyserver-options auto-key-retrieve --receive-keys"

alias luamake=/home/baleksa/repositories/lua-language-server/3rd/luamake/luamake

alias m="git checkout main"
alias s="git checkout stable"
alias gc="git commit"
alias ga="git add"
alias gs="git status"
alias gp="git push"
alias gd="git diff"

alias ls='ls --color=auto'
alias pip='pip3'
alias la='ls -a'
alias ll='ls -la'
alias xqr='xbps-query -Rs'
alias xr='sudo xbps-remove'
alias luamake='/home/baleksa/Repositories/lua-language-server/3rd/luamake/luamake'
alias clangse='clang -Wall -g3 -Werror -pedantic -std=c11'
alias c='clang -Wall -g3 -Werror -pedantic -std=c11'
alias c++='clang++ -Wall -g3 -Werror -pedantic -std=c++11'
alias t='todo.sh -d ~/.config/todo/todo.conf'
alias es='edit_script.sh'
alias u='update_all.sh'
alias d='sdcv'
alias st='sync_todo.sh'
alias stc='rclone bisync gdrive_void_hpi5:todo /home/baleksa/Documents/todo --exclude "todo.txt.bak" --exclude "report.txt"'
alias p='ps aux | grep '
