#!/bin/sh
# HISTFILE="$XDG_DATA_HOME"/zsh/history

HISTSIZE=1000000
SAVEHIST=1000000

export FZF_DEFAULT_COMMAND='fd -H .'
export FZF_CTRL_R_OPTS='--layout=reverse'

export MANPAGER='nvim +Man!'
export MANWIDTH=999

export EDITOR=nvim
export QT_QPA_PLATFORM=wayland-egl
export XDG_SESSION_TYPE=wayland 
export XDG_CURRENT_DESKTOP=sway

export VOIDNSRUN_DIR=/glibc
export VOIDNSUNDO_BIN=/usr/local/bin/voidnsundo

export STARDICT_DATA_DIR=~/.config/stardict

#export GTK_BACKED=wayland
eval "$(zoxide init zsh)"

# eval "$(fnm env)"
# eval "`pip completion --zsh`"


# # >>> conda initialize >>>
# # !! Contents within this block are managed by 'conda init' !!
# __conda_setup="$("$HOME/.miniconda/bin/conda" 'shell.zsh' 'hook' 2> /dev/null)"
# if [ $? -eq 0 ]; then
#     eval "$__conda_setup"
# else
#     if [ -f "$HOME/.miniconda/etc/profile.d/conda.sh" ]; then
#         . "$HOME/.miniconda/etc/profile.d/conda.sh"
#     else
#         export PATH="$HOME/.miniconda/bin:$PATH"
#     fi
# fi
# unset __conda_setup
# # <<< conda initialize <<<

