#!/bin/sh

light -S 15

oldswaybg="$(pidof swaybg)"
swaybg -i ~/Pictures/book_room_forest.png -o \* -m fill &
kill "$oldswaybg"

makoctl set-mode dark

gsettings set org.gnome.desktop.interface gtk-theme "Arc-Dark"
gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

notify-send --app-name="darkman" --urgency=low --icon=/usr/share/icons/gnome/32x32/status/weather-clear-night.png "Switching to dark mode"
